### ISSUE TITLE
css 如何实现左侧固定300px，右侧自适应的布局

### ISSUE THREAD

**Issue by gg8899** [gg8899/fe-interview#245]
1. 使用`flex`布局
.container
  .left
  .main

```css
.container {
  display: flex;
}

.left {
  flex-basis: 300px;
  flex-shrink: 0;
}

.main {
  flex-grow: 1;
 // flex: 1
}
```

2. 只使用 Grid 布局
```css
.container {
  display: grid;
  grid-template-columns: 300px 1fr;
}
```

3. 使用calc方法 .left{width:330px;} .right{width: calc(100% - 330px)}

4. 圣杯布局吧， float也可以
5. 浮动+BFC
