### ISSUE TITLE
使用 CSS 如何画一个三角形

### ISSUE THREAD

**Issue by gg8899** [gg8899/fe-interview#259]
思路：利用 `boder`的上下左右大小作为图形的填充距离，再将不想显示的部分用透明色填充。。

代码样式
```css
        
        .box {
            width: 0;
            height: 0;
            border: 250px solid red;
            border-color: transparent transparent transparent red;
        }


        .bbox {
            width: 50vh;
            height: 50vh;
            background-color: aqua;
            //   polygon(x1 y1, x2 y2, x3 y3, x4 y4, xn yn)
           // 这将创建一个矩形形状，其大小与其父内容相同，通过指定其四个角的坐标：左上角（0% 0%）、右上角（100% 0%）、右下角（100% 100%）和左下角（0% 100%）。
          // 从左上角到左下角到右下脚 保留 整个图形的。
            clip-path: polygon(0 0, 0% 100%, 100% 100%);
        }
```

思路二：借助`clip-path` 属性中的 `polygon()` 函数裁剪一个三角形。
