### ISSUE TITLE
如何实现网页的加载进度条

### ISSUE THREAD

**Issue by gg8899** [gg8899/fe-interview#263]
nprogress 工具可实现

拆分成两个问题：
1. 怎么获取进度
    - 借助 `axios` 的 `onUnloadProgress` 方法
    ```js
            onUnloadProgress(e) {   
                 const complete = e.loaded / e.total * 100
            }
    ```
    - html 去遍历 `link.url`，`script.src ` 给他们加上 `onLoad` 事件。 然后 loaded / total 
    -给最后一个加载的标签加上 `onL:oad` 事件。在加载完成之前做一个缓慢增长的模拟，事件加载完成。就显示加载完成。
2. 怎么实现进度条

```html
用来显示一已知范围的标量值或者分数值
<meter max=""  value=""></meter>

用来显示一项任务的完成进度，通常情况下该元素都显示为一个进度条。
<progress  max=""  value=""></progress>

<div class="g-progress" style="--progress:  50%"></div>
```

```css
.g-progress {
     background: liner-gradient(90deg, #0f0, #0ff, var(--progress), transparent, 0 )
}

```
