### ISSUE TITLE
placeholder实现的两种方式

### ISSUE THREAD

**Issue by gg8899** [gg8899/fe-interview#267]
- 使用input的value作为显示文本
- 不使用value，添加一个额外的标签（span）到body里然后绝对定位覆盖到input上面

```html

<label for="first-name">Your phone number:</label><br />

<input
  id="first-name"
  type="tel"
  name="phone"
  minlength="9"
  maxlength="9"
  placeholder="It must be 9 digits" />


```

```css
input {
  margin-top: 0.5rem;
}

input::placeholder {
  font-weight: bold;
  opacity: 0.5;
  color: red;
}
```
