### ISSUE TITLE
一个列表的每个底部加上下划线，最后一个不加。有什么优雅的写法

### ISSUE THREAD

**Issue by gg8899** [gg8899/fe-interview#84]
假设是多个 li 标签，可以设置 
```css
p + p {
   border-top: 1px solid  #ccc; 
}
```
